SELECT
    c.CART_ID,
    CASE WHEN SUM(cp.PRICE) < c.MINIMUM_REQUIREMENT THEN 1 ELSE 0 END AS ABUSED
FROM COUPONS c
         JOIN CART_PRODUCTS cp ON c.CART_ID = cp.CART_ID
GROUP BY c.CART_ID, c.MINIMUM_REQUIREMENT
ORDER BY c.CART_ID;