SELECT CART_ID, CASE
                    WHEN TOTAL_PRICE > MINIMUM_REQUIREMENT THEN 1
                    ELSE 0
                END AS ABUSED
FROM (
    SELECT CART_ID, SUM(PRICE) TOTAL_PRICE
    FROM CART_PRODUCTS
    GROUP BY CART_ID
) CART JOIN COUPONS ON CART.CART_ID = COUPONS.CART_ID
ORDER BY CART_ID;